# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bgpd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import grpc_lib.common_pb2 as common__pb2
import grpc_lib.interface_pb2 as interface__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bgpd.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbgpd.proto\x1a\x0c\x63ommon.proto\x1a\x0finterface.proto\"x\n\x10\x42GPConfigRequest\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.ConfigRequest\x12\x1a\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\n.BGPConfig\x12\r\n\x05\x63ount\x18\x03 \x01(\r\x12\x18\n\x04step\x18\x04 \x01(\x0b\x32\n.BGPConfig\"e\n\tBGPConfig\x12%\n\x0bpeer_config\x18\x01 \x01(\x0b\x32\x0e.BGPPeerConfigH\x00\x12\'\n\x0croute_config\x18\x02 \x01(\x0b\x32\x0f.BGPRouteConfigH\x00\x42\x08\n\x06\x65ntity\"\xe0\x01\n\rBGPPeerConfig\x12\x12\n\npeer_index\x18\x01 \x01(\r\x12\x0f\n\x07peer_id\x18\x02 \x01(\t\x12(\n\x04type\x18\x03 \x01(\x0e\x32\x1a.BGPPeerConfig.SessionType\x12#\n\tinterface\x18\x04 \x01(\x0b\x32\x10.InterfaceConfig\x12\x0e\n\x06\x64ut_ip\x18\x05 \x01(\t\x12\x11\n\tas_number\x18\x06 \x01(\r\x12\x15\n\rdut_as_number\x18\x07 \x01(\r\"!\n\x0bSessionType\x12\x08\n\x04\x45\x42GP\x10\x00\x12\x08\n\x04IBGP\x10\x01\"\x82\x01\n\x0e\x42GPRouteConfig\x12\x12\n\npeer_index\x18\x01 \x01(\r\x12\x13\n\x0broute_index\x18\x02 \x01(\r\x12\r\n\x05route\x18\x03 \x01(\t\x12\x12\n\nroute_mask\x18\x04 \x01(\r\x12\x13\n\x0broute_count\x18\x05 \x01(\r\x12\x0f\n\x07nexthop\x18\x06 \x01(\t2\xa1\x01\n\x03\x42GP\x12\x30\n\x0cStartService\x12\r.StartRequest\x1a\x0f.StatusResponse\"\x00\x12.\n\x0bStopService\x12\x0c.StopRequest\x1a\x0f.StatusResponse\"\x00\x12\x38\n\x10\x43onfigureService\x12\x11.BGPConfigRequest\x1a\x0f.StatusResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,interface__pb2.DESCRIPTOR,])



_BGPPEERCONFIG_SESSIONTYPE = _descriptor.EnumDescriptor(
  name='SessionType',
  full_name='BGPPeerConfig.SessionType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EBGP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IBGP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=462,
  serialized_end=495,
)
_sym_db.RegisterEnumDescriptor(_BGPPEERCONFIG_SESSIONTYPE)


_BGPCONFIGREQUEST = _descriptor.Descriptor(
  name='BGPConfigRequest',
  full_name='BGPConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='BGPConfigRequest.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='BGPConfigRequest.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='BGPConfigRequest.count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step', full_name='BGPConfigRequest.step', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=165,
)


_BGPCONFIG = _descriptor.Descriptor(
  name='BGPConfig',
  full_name='BGPConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_config', full_name='BGPConfig.peer_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_config', full_name='BGPConfig.route_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='entity', full_name='BGPConfig.entity',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=167,
  serialized_end=268,
)


_BGPPEERCONFIG = _descriptor.Descriptor(
  name='BGPPeerConfig',
  full_name='BGPPeerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_index', full_name='BGPPeerConfig.peer_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='BGPPeerConfig.peer_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='BGPPeerConfig.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface', full_name='BGPPeerConfig.interface', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dut_ip', full_name='BGPPeerConfig.dut_ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='as_number', full_name='BGPPeerConfig.as_number', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dut_as_number', full_name='BGPPeerConfig.dut_as_number', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BGPPEERCONFIG_SESSIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=495,
)


_BGPROUTECONFIG = _descriptor.Descriptor(
  name='BGPRouteConfig',
  full_name='BGPRouteConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_index', full_name='BGPRouteConfig.peer_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_index', full_name='BGPRouteConfig.route_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route', full_name='BGPRouteConfig.route', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_mask', full_name='BGPRouteConfig.route_mask', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_count', full_name='BGPRouteConfig.route_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nexthop', full_name='BGPRouteConfig.nexthop', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=628,
)

_BGPCONFIGREQUEST.fields_by_name['request'].message_type = common__pb2._CONFIGREQUEST
_BGPCONFIGREQUEST.fields_by_name['config'].message_type = _BGPCONFIG
_BGPCONFIGREQUEST.fields_by_name['step'].message_type = _BGPCONFIG
_BGPCONFIG.fields_by_name['peer_config'].message_type = _BGPPEERCONFIG
_BGPCONFIG.fields_by_name['route_config'].message_type = _BGPROUTECONFIG
_BGPCONFIG.oneofs_by_name['entity'].fields.append(
  _BGPCONFIG.fields_by_name['peer_config'])
_BGPCONFIG.fields_by_name['peer_config'].containing_oneof = _BGPCONFIG.oneofs_by_name['entity']
_BGPCONFIG.oneofs_by_name['entity'].fields.append(
  _BGPCONFIG.fields_by_name['route_config'])
_BGPCONFIG.fields_by_name['route_config'].containing_oneof = _BGPCONFIG.oneofs_by_name['entity']
_BGPPEERCONFIG.fields_by_name['type'].enum_type = _BGPPEERCONFIG_SESSIONTYPE
_BGPPEERCONFIG.fields_by_name['interface'].message_type = interface__pb2._INTERFACECONFIG
_BGPPEERCONFIG_SESSIONTYPE.containing_type = _BGPPEERCONFIG
DESCRIPTOR.message_types_by_name['BGPConfigRequest'] = _BGPCONFIGREQUEST
DESCRIPTOR.message_types_by_name['BGPConfig'] = _BGPCONFIG
DESCRIPTOR.message_types_by_name['BGPPeerConfig'] = _BGPPEERCONFIG
DESCRIPTOR.message_types_by_name['BGPRouteConfig'] = _BGPROUTECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BGPConfigRequest = _reflection.GeneratedProtocolMessageType('BGPConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _BGPCONFIGREQUEST,
  '__module__' : 'bgpd_pb2'
  # @@protoc_insertion_point(class_scope:BGPConfigRequest)
  })
_sym_db.RegisterMessage(BGPConfigRequest)

BGPConfig = _reflection.GeneratedProtocolMessageType('BGPConfig', (_message.Message,), {
  'DESCRIPTOR' : _BGPCONFIG,
  '__module__' : 'bgpd_pb2'
  # @@protoc_insertion_point(class_scope:BGPConfig)
  })
_sym_db.RegisterMessage(BGPConfig)

BGPPeerConfig = _reflection.GeneratedProtocolMessageType('BGPPeerConfig', (_message.Message,), {
  'DESCRIPTOR' : _BGPPEERCONFIG,
  '__module__' : 'bgpd_pb2'
  # @@protoc_insertion_point(class_scope:BGPPeerConfig)
  })
_sym_db.RegisterMessage(BGPPeerConfig)

BGPRouteConfig = _reflection.GeneratedProtocolMessageType('BGPRouteConfig', (_message.Message,), {
  'DESCRIPTOR' : _BGPROUTECONFIG,
  '__module__' : 'bgpd_pb2'
  # @@protoc_insertion_point(class_scope:BGPRouteConfig)
  })
_sym_db.RegisterMessage(BGPRouteConfig)



_BGP = _descriptor.ServiceDescriptor(
  name='BGP',
  full_name='BGP',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=631,
  serialized_end=792,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartService',
    full_name='BGP.StartService',
    index=0,
    containing_service=None,
    input_type=common__pb2._STARTREQUEST,
    output_type=common__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StopService',
    full_name='BGP.StopService',
    index=1,
    containing_service=None,
    input_type=common__pb2._STOPREQUEST,
    output_type=common__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConfigureService',
    full_name='BGP.ConfigureService',
    index=2,
    containing_service=None,
    input_type=_BGPCONFIGREQUEST,
    output_type=common__pb2._STATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BGP)

DESCRIPTOR.services_by_name['BGP'] = _BGP

# @@protoc_insertion_point(module_scope)
