# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_lib.common_pb2 as common__pb2
import grpc_lib.interface_pb2 as interface__pb2


class InterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfigureInterface = channel.unary_unary(
                '/Interface/ConfigureInterface',
                request_serializer=interface__pb2.InterfaceConfigRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                )


class InterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConfigureInterface(self, request, context):
        """Configure interface.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfigureInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureInterface,
                    request_deserializer=interface__pb2.InterfaceConfigRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Interface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Interface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConfigureInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Interface/ConfigureInterface',
            interface__pb2.InterfaceConfigRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
